CREATE DATABASE gestao;
USE gestao;

CREATE TABLE produtos (
produtoId INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
nome VARCHAR (100) NOT NULL,
preco VARCHAR (50) NOT NULL,
fabricante VARCHAR (100) NOT NULL);

CREATE TABLE garantia (
garantiaId INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
tipo VARCHAR (100) NOT NULL,
dtInicio DATE NOT NULL,
dtTermino DATE NOT NULL, 
termos VARCHAR (100) NOT NULL);